### PR TITLE
refactor: adapt to Obsi v0.15+

### PR DESCRIPTION
**Pull request by kometenstaub**
I've adapted the Codemirror imports to Obsidian v0.15+.

They didn't fail yet, but probably the old exports will be removed at some point.

I also bumped the version in the manifest, so if this gets merged, it would need a git tag so that updates don't fail in Obsidian v0.15+

I've also updated versions.json.

### CODE REVIEW

**Comment by Clemens-E** [comment]
Hi, thanks for the work!
Sadly, I'm not up-to-date on Obsidians Changes.
I'm uncertain if I understand what you mean with the git tag. Is a new release with version "0.3.0" not sufficient?

**Comment by kometenstaub** [comment]
Oh yes, it sure is. It's just because you have a github action that works with a git tag, that pushing this tag would make the release, that's all.
However you normally do releases, a 0.3.0 release should work.

**Comment by Clemens-E** [comment]
🤦‍♂️ yeah, you know more about my repo than me. Thank you.

**Comment by kometenstaub** [comment]
The new build is public, so I think this PR can be merged now.

**Pull request merged**
