### PR TITLE
Notifications about network issues should only be displayed once

### PR DESCRIPTION
**Pull request by brandones**
At present, there is a failure, a notification will be displayed every time document checking happens. If auto-checking is on, it will appear over and over, disappearing and reappearing every few seconds.

This PR makes it so that repeat notifications are suppressed when auto-checking.

Sorry the video is so long, but it shows both the present behavior and new behavior.

https://github.com/Clemens-E/obsidian-languagetool-plugin/assets/1031876/b89a872c-ed28-48f8-9490-9a8338d8491e

### CODE REVIEW

**Comment by Clemens-E** [comment]
I will add typings to the status and then merge it, thanks for the PR!
and sorry for not merging this sooner

**Comment by MartinJDavis93** [comment]
@brandones Thank you, this is a great PR, but there's a slightly inconvenient aspect while working – the notification doesn't close automatically. To close it, you've to click on it, which isn't very convenient. It'd be great if you could fix this. Thanks again.

**Comment by Clemens-E** [comment]
I modified this so the notification hides after 3 Seconds.
You can update the plugin to see the change

**Comment by MartinJDavis93** [comment]
> I modified this so the notification hides after 3 Seconds. You can update the plugin to see the change

Updated, everything works great! Thank you kindly.

**Pull request merged**
