### PR TITLE
add commands to accept suggestions under cursor

### PR DESCRIPTION
**Pull request by hpr1999**
This adds commands to the plugin that will replace the text under the cursor.
This could be a first draft to address #46 

<details>
<summary>The change at work</summary>

image

image

image
</details>

While it works on my machine (I have not yet tested on mobile at this time) I'm not quite sure if it fits well into the architecture and it somewhat duplicates code from `tooltipField.ts`. That's simply because I haven't used CodeMirror before today.

I have not found a possibility to invoke the button handler from a command. I think it might be possible the other way round, but I didn't want to advocate such a refactor out of the blue. 

Is this still acceptable to you or do you have some suggestions how to accomplish this another way?

### CODE REVIEW

**Comment by Clemens-E** [comment]
Looks good actually, but I'm not certain how people want this feature implemented.
A different option I just tried is adding a single command (instead of three) to rotate through all suggestions in an open tooltip.

**Comment by hpr1999** [comment]
I pretty much went this way because it seemed easiest to integrate with a hotkeyable command. Do you mean rotating through the tooltip UI or simply accepting them one after another? Would this require not clearing the underline after accepting?

**Comment by Clemens-E** [comment]
Okay, so basically, adding a command to jump to the next position where an underline is.
roughly
```ts
const cursorOffset = editor.posToOffset(editor.getCursor());
editorView.state.field(underlineField).between(cursorOffset, Infinity, (from, to, value) => {
// only do this for the first one
editorView.dispatch({ selection: { anchor: from, head: to } });
});
```
this jumps to the next grammar issue and that will cause the tooltip to show

then there is a command to rotate through the corrections in the open tooltip
```ts
const buttons = Array.from(document.querySelectorAll('.lt-buttoncontainer'));
const index = /* whatever logic to get currently selected button index + 1 or 0*/
// unselect all buttons
// select next button
buttons[index].style.background = 'red'; // for example
buttons[index].classList.add('selected');

```

And then either another command to use that correction or keydown event, if that works.

Does that make sense?

**Comment by hpr1999** [comment]
Yeah I guess that'd work too. 

For the first one:
- This seems like a good command to have, no matter whether to go ahead with my implementation or change it up as you suggest. Should speed up both methods. 
- I'm unsure if I've read the documentation right, but I think the `between` method does not guarantee any order in which the underlines will be given, so I don't know how to get the first. 

For the second one: 
- Personally, I feel like it would be slightly less convenient to have to press "rotate" twice _and_ "accept". 
However, it's good that this method has some visuals. 
- The methods don't really prevent each other from existing, one could have both (although this seems a little redundant)
- It's your project, so you can just make a call or we could ask for opinions in #46

**Comment by Clemens-E** [comment]
Yeah, when I think about it, you are right, rotating through the suggestions is quite annoying, having direct commands (like your implementation) makes more sense.
I read the same thing from the `between` method, probably sorting by `from` makes sense here, I was just writing some pseudocode.

**Comment by hpr1999** [comment]
So to go forward with this, should I have a look at perhaps adding a "jump to next suggestion" command as in your code block? 
Or is there anything else still open?

**Comment by Clemens-E** [comment]
I don't mind making the adjustments, unless you insist on doing them, I will do them this week.

**Comment by hpr1999** [comment]
Oh feel free if you wish.

**Comment by Clemens-E** [comment]
Sorry for that add license commit, wasn't meant for this branch.
Thanks for the contribution!

**Comment by hpr1999** [comment]
No worries and you're welcome, happy it made it in.

**Pull request merged**
